apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: 'https://github.com/ak-techo/test-argocd-team-b.git'
      path: proj-dash-app
      targetRevision: main
    - repoURL: 'https://github.com/ak-techo/test-argocd-team-b.git'
      path: proj-olympus-app
      targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s