apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-roles
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ak-techo/test-argocd-team-a.git'
    path: sub-chart
    targetRevision: main
    helm:
      valueFiles:
      - dev-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s